<?xml version="1.0" encoding="UTF-8"?>
<project xmlns="http://maven.apache.org/POM/4.0.0" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xsi:schemaLocation="http://maven.apache.org/POM/4.0.0 http://maven.apache.org/xsd/maven-4.0.0.xsd">
  <modelVersion>4.0.0</modelVersion>

  <parent>
    <groupId>io.vanillabp</groupId>
    <artifactId>release-parent</artifactId>
    <version>1.1.0</version>
  </parent>

  <artifactId>adapters-common</artifactId>
  <version>0.0.1-SNAPSHOT</version>
  <packaging>pom</packaging>
  <name>Common stuff used by all VanillaBP adapters</name>

  <licenses>
    <license>
      <name>Apache License, Version 2.0</name>
      <url>http://www.apache.org/licenses/LICENSE-2.0.txt</url>
      <distribution>repo</distribution>
    </license>
  </licenses>

  <developers>
    <developer>
      <id>VanillaBP</id>
      <organization>Phactum Softwareentwicklung GmbH</organization>
      <organizationUrl>https://www.phactum.at</organizationUrl>
    </developer>
  </developers>

  <modules>
    <module>migration-adapter</module>
    <module>spring-boot-integration</module>
    <module>quarkus-integration</module>
    <module>jacoco-report</module>
  </modules>

  <distributionManagement>
    <snapshotRepository>
      <id>github</id>
      <name>Github Packages</name>
      <url>https://maven.pkg.github.com/vanillabp/adapters-common</url>
    </snapshotRepository>
  </distributionManagement>

  <properties>
    <root.project.version>0.0.1-SNAPSHOT</root.project.version>
    <project.build.sourceEncoding>UTF-8</project.build.sourceEncoding>
    <project.reporting.outputEncoding>UTF-8</project.reporting.outputEncoding>
    <vanillabp.version>1.0.2</vanillabp.version>
    <version.java>21</version.java>
    <lombok.version>1.18.34</lombok.version>
    <jacoco.version>0.8.12</jacoco.version>
    <surefire-plugin.version>3.5.2</surefire-plugin.version>
    <failsafe-plugin.version>3.5.2</failsafe-plugin.version>
  </properties>

  <dependencyManagement>
    <dependencies>
      <dependency>
        <groupId>io.vanillabp</groupId>
        <artifactId>spi-for-java</artifactId>
        <version>${vanillabp.version}</version>
      </dependency>
      <dependency>
        <groupId>org.projectlombok</groupId>
        <artifactId>lombok</artifactId>
        <version>${lombok.version}</version>
        <optional>true</optional>
      </dependency>
      <dependency>
        <groupId>org.slf4j</groupId>
        <artifactId>slf4j-api</artifactId>
        <version>2.0.17</version>
      </dependency>
    </dependencies>
  </dependencyManagement>

  <build>
    <pluginManagement>
      <plugins>
        <plugin>
          <groupId>org.apache.maven.plugins</groupId>
          <artifactId>maven-compiler-plugin</artifactId>
          <version>3.14.0</version>
          <configuration>
            <release>${version.java}</release>
            <annotationProcessorPaths>
              <path>
                <groupId>org.projectlombok</groupId>
                <artifactId>lombok</artifactId>
                <version>${lombok.version}</version>
              </path>
            </annotationProcessorPaths>
          </configuration>
        </plugin>
        <plugin>
          <groupId>com.diffplug.spotless</groupId>
          <artifactId>spotless-maven-plugin</artifactId>
          <version>2.44.0</version>
          <configuration>
            <pom>
              <includes>
                <include>**/pom.xml</include>
              </includes>
              <excludes>
                <exclude>**/target/**/</exclude>
                <exclude>**/node_modules/**/</exclude>
              </excludes>
              <sortPom></sortPom>
            </pom>
            <markdown>
              <includes>
                <include>**/*.md</include>
              </includes>
              <excludes>
                <exclude>**/target/**/</exclude>
                <exclude>**/node_modules/**/</exclude>
              </excludes>
              <flexmark></flexmark>
            </markdown>
            <yaml>
              <includes>
                <include>**/*.yaml</include>
              </includes>
              <excludes>
                <exclude>**/target/**/</exclude>
                <exclude>**/node_modules/**/</exclude>
              </excludes>
              <jackson>
                <yamlFeatures>
                  <MINIMIZE_QUOTES>true</MINIMIZE_QUOTES>
                  <WRITE_DOC_START_MARKER>false</WRITE_DOC_START_MARKER>
                </yamlFeatures>
              </jackson>
              <prettier></prettier>
            </yaml>
            <java>
              <eclipse>
                <!-- https://help.eclipse.org/latest/index.jsp?topic=%2Forg.eclipse.jdt.doc.isv%2Freference%2Fapi%2Forg%2Feclipse%2Fjdt%2Fcore%2Fformatter%2FDefaultCodeFormatterConstants.html -->
                <file>${maven.multiModuleProjectDirectory}/formatting_conventions.xml</file>
                <version>4.35</version>
              </eclipse>
              <removeUnusedImports></removeUnusedImports>
              <importOrder>
                <order>java,javax,org,com,at.phactum</order>
              </importOrder>
            </java>
          </configuration>
          <executions>
            <execution>
              <goals>
                <goal>check</goal>
              </goals>
              <phase>process-sources</phase>
            </execution>
          </executions>
        </plugin>
        <plugin>
          <artifactId>maven-surefire-plugin</artifactId>
          <version>${surefire-plugin.version}</version>
        </plugin>
      </plugins>
    </pluginManagement>
    <plugins>
      <plugin>
        <groupId>com.diffplug.spotless</groupId>
        <artifactId>spotless-maven-plugin</artifactId>
      </plugin>
      <plugin>
        <groupId>org.apache.maven.plugins</groupId>
        <artifactId>maven-source-plugin</artifactId>
        <executions>
          <execution>
            <id>attach-sources</id>
            <goals>
              <goal>jar</goal>
            </goals>
          </execution>
        </executions>
      </plugin>
      <plugin>
        <groupId>org.jacoco</groupId>
        <artifactId>jacoco-maven-plugin</artifactId>
        <version>${jacoco.version}</version>
        <configuration>
          <sessionId>anonymous-session-id</sessionId>
        </configuration>
        <executions>
          <execution>
            <goals>
              <goal>prepare-agent</goal>
            </goals>
          </execution>
        </executions>
      </plugin>
    </plugins>
  </build>
</project>
