<?xml version="1.0" encoding="UTF-8"?>
<project xmlns="http://maven.apache.org/POM/4.0.0" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xsi:schemaLocation="http://maven.apache.org/POM/4.0.0 http://maven.apache.org/xsd/maven-4.0.0.xsd">
  <modelVersion>4.0.0</modelVersion>

  <parent>
    <groupId>io.vanillabp</groupId>
    <artifactId>release-parent</artifactId>
    <version>1.1.0</version>
  </parent>

  <artifactId>adapter-platform-integration</artifactId>
  <version>2.0.0-SNAPSHOT</version>
  <packaging>pom</packaging>
  <name>VanillaBP adapter platform integration</name>

  <licenses>
    <license>
      <name>Apache License, Version 2.0</name>
      <url>http://www.apache.org/licenses/LICENSE-2.0.txt</url>
      <distribution>repo</distribution>
    </license>
  </licenses>

  <developers>
    <developer>
      <id>VanillaBP</id>
      <organization>Phactum Softwareentwicklung GmbH</organization>
      <organizationUrl>https://www.phactum.at</organizationUrl>
    </developer>
  </developers>

  <modules>
    <module>test-utils</module>
    <module>migration-adapter</module>
    <module>spring-boot-integration</module>
    <module>quarkus-integration</module>
    <module>test-coverage-report</module>
  </modules>

  <distributionManagement>
    <snapshotRepository>
      <id>github</id>
      <name>Github Packages</name>
      <url>https://maven.pkg.github.com/vanillabp/adapter-platform-integration</url>
    </snapshotRepository>
  </distributionManagement>

  <properties>
    <project.build.sourceEncoding>UTF-8</project.build.sourceEncoding>
    <project.reporting.outputEncoding>UTF-8</project.reporting.outputEncoding>
    <vanillabp.version>1.1.0-SNAPSHOT</vanillabp.version>
    <version.java>21</version.java>
    <lombok.version>1.18.34</lombok.version>
    <transaction-outbox.version>6.1.653</transaction-outbox.version>
    <jacoco.version>0.8.13</jacoco.version>
    <mockito.version>5.17.0</mockito.version>
    <testcontainers.version>2.0.1</testcontainers.version>
  </properties>

  <dependencyManagement>
    <dependencies>
      <dependency>
        <groupId>io.vanillabp</groupId>
        <artifactId>spi-for-java</artifactId>
        <version>${vanillabp.version}</version>
      </dependency>
      <dependency>
        <groupId>org.projectlombok</groupId>
        <artifactId>lombok</artifactId>
        <version>${lombok.version}</version>
        <optional>true</optional>
      </dependency>
      <dependency>
        <groupId>org.slf4j</groupId>
        <artifactId>slf4j-api</artifactId>
        <version>2.0.17</version>
      </dependency>
      <dependency>
        <groupId>org.testcontainers</groupId>
        <artifactId>testcontainers</artifactId>
        <version>${testcontainers.version}</version>
      </dependency>
      <dependency>
        <groupId>org.testcontainers</groupId>
        <artifactId>junit-jupiter</artifactId>
        <version>${testcontainers.version}</version>
      </dependency>
      <dependency>
        <groupId>org.testcontainers</groupId>
        <artifactId>testcontainers-mongodb</artifactId>
        <version>${testcontainers.version}</version>
      </dependency>
    </dependencies>
  </dependencyManagement>

  <build>
    <pluginManagement>
      <plugins>
        <plugin>
          <groupId>org.apache.maven.plugins</groupId>
          <artifactId>maven-compiler-plugin</artifactId>
          <version>3.15.0</version>
          <configuration>
            <release>${version.java}</release>
            <annotationProcessorPaths>
              <path>
                <groupId>org.projectlombok</groupId>
                <artifactId>lombok</artifactId>
                <version>${lombok.version}</version>
              </path>
            </annotationProcessorPaths>
          </configuration>
        </plugin>
        <plugin>
          <artifactId>maven-failsafe-plugin</artifactId>
          <version>3.5.2</version>
        </plugin>
        <plugin>
          <artifactId>maven-surefire-plugin</artifactId>
          <version>3.5.2</version>
          <configuration>
            <!-- see https://javadoc.io/doc/org.mockito/mockito-core/latest/org.mockito/org/mockito/Mockito.html#mockito-instrumentation -->
            <!-- property 'jacoco.agent' is filled by jacoco-maven-plugin blow in this file -->
            <argLine>@{jacoco.agent} -Xshare:off -javaagent:${settings.localRepository}/org/mockito/mockito-core/${mockito.version}/mockito-core-${mockito.version}.jar</argLine>
          </configuration>
          <dependencies>
            <dependency>
              <groupId>org.mockito</groupId>
              <artifactId>mockito-core</artifactId>
              <version>${mockito.version}</version>
            </dependency>
          </dependencies>
        </plugin>
      </plugins>
    </pluginManagement>
    <plugins>
      <plugin>
        <groupId>com.diffplug.spotless</groupId>
        <artifactId>spotless-maven-plugin</artifactId>
        <version>3.1.0</version>
        <configuration>
          <pom>
            <includes>
              <include>**/pom.xml</include>
            </includes>
            <excludes>
              <exclude>**/target/**/</exclude>
              <exclude>**/node_modules/**/</exclude>
            </excludes>
            <sortPom>
              <quiet>true</quiet>
            </sortPom>
          </pom>
          <markdown>
            <includes>
              <include>**/*.md</include>
            </includes>
            <excludes>
              <exclude>**/target/**/</exclude>
              <exclude>**/node_modules/**/</exclude>
            </excludes>
            <flexmark/>
          </markdown>
          <yaml>
            <includes>
              <include>**/*.yaml</include>
            </includes>
            <excludes>
              <exclude>**/target/**/</exclude>
              <exclude>**/node_modules/**/</exclude>
            </excludes>
            <jackson>
              <yamlFeatures>
                <MINIMIZE_QUOTES>true</MINIMIZE_QUOTES>
                <WRITE_DOC_START_MARKER>false</WRITE_DOC_START_MARKER>
                <INDENT_ARRAYS_WITH_INDICATOR>true</INDENT_ARRAYS_WITH_INDICATOR>
              </yamlFeatures>
            </jackson>
          </yaml>
          <java>
            <eclipse>
              <!-- https://help.eclipse.org/latest/index.jsp?topic=%2Forg.eclipse.jdt.doc.isv%2Freference%2Fapi%2Forg%2Feclipse%2Fjdt%2Fcore%2Fformatter%2FDefaultCodeFormatterConstants.html -->
              <file>${maven.multiModuleProjectDirectory}/formatting_conventions.xml</file>
              <version>4.35</version>
            </eclipse>
            <removeUnusedImports/>
            <importOrder>
              <order>java,javax,org,com,at.phactum</order>
            </importOrder>
          </java>
        </configuration>
        <executions>
          <execution>
            <goals>
              <goal>check</goal>
            </goals>
            <phase>process-sources</phase>
          </execution>
        </executions>
      </plugin>
      <plugin>
        <groupId>org.apache.maven.plugins</groupId>
        <artifactId>maven-source-plugin</artifactId>
        <executions>
          <execution>
            <id>attach-sources</id>
            <goals>
              <goal>jar</goal>
            </goals>
          </execution>
        </executions>
      </plugin>
      <plugin>
        <groupId>org.jacoco</groupId>
        <artifactId>jacoco-maven-plugin</artifactId>
        <version>${jacoco.version}</version>
        <configuration>
          <sessionId>anonymous-session-id</sessionId>
          <!-- exclude test classes and main-classes needed by integration tests -->
          <excludes>
            <exclude>io/vanillabp/integration/test/**</exclude>
            <exclude>io/vanillabp/integration/it/**</exclude>
          </excludes>
          <!-- stores javaagent JVM-parameter into property to be used by Quarkus which starts additional JVMs
                      to run integration tests -->
          <propertyName>jacoco.agent</propertyName>
        </configuration>
        <executions>
          <execution>
            <goals>
              <goal>prepare-agent</goal>
            </goals>
          </execution>
        </executions>
      </plugin>
    </plugins>
  </build>
</project>
