<?xml version="1.0" encoding="UTF-8"?>
<project xmlns="http://maven.apache.org/POM/4.0.0" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xsi:schemaLocation="http://maven.apache.org/POM/4.0.0 https://maven.apache.org/xsd/maven-4.0.0.xsd">
  <modelVersion>4.0.0</modelVersion>

  <parent>
    <groupId>io.vanillabp</groupId>
    <artifactId>adapter-platform-integration</artifactId>
    <version>0.0.1-SNAPSHOT</version>
  </parent>

  <artifactId>quarkus-integration-parent</artifactId>
  <packaging>pom</packaging>
  <name>Quarkus Integration</name>

  <modules>
    <module>quarkus-support</module>
    <module>deployment</module>
    <module>runtime</module>
    <module>dummy-adapter</module>
    <module>integration-tests</module>
  </modules>

  <properties>
    <quarkus.version>3.25.3</quarkus.version>
  </properties>

  <dependencyManagement>
    <dependencies>
      <dependency>
        <groupId>io.quarkus</groupId>
        <artifactId>quarkus-bom</artifactId>
        <version>${quarkus.version}</version>
        <type>pom</type>
        <scope>import</scope>
      </dependency>
    </dependencies>
  </dependencyManagement>

  <build>
    <pluginManagement>
      <plugins>
        <plugin>
          <groupId>io.quarkus</groupId>
          <artifactId>quarkus-maven-plugin</artifactId>
          <version>${quarkus.version}</version>
        </plugin>
        <plugin>
          <artifactId>maven-surefire-plugin</artifactId>
          <configuration>
            <systemPropertyVariables>
              <java.util.logging.manager>org.jboss.logmanager.LogManager</java.util.logging.manager>
              <maven.home>${maven.home}</maven.home>
              <maven.repo>${settings.localRepository}</maven.repo>
              <!-- passed to quarkus prod tests for tracking of coverage -->
              <jacoco.agent>${settings.localRepository}/org/jacoco/org.jacoco.agent/${jacoco.version}/org.jacoco.agent-${jacoco.version}-runtime.jar=destfile=${project.build.directory}/jacoco-it.exec,append=true,includes=io/vanillabp/integration/deployment/**:io/vanillabp/integration/adapter/migration/**:io/vanillabp/integration/runtime/**,sessionid=anonymous-session-id</jacoco.agent>
              <maven.project.version>${project.version}</maven.project.version>
            </systemPropertyVariables>
          </configuration>
        </plugin>
        <plugin>
          <artifactId>maven-failsafe-plugin</artifactId>
          <configuration>
            <systemPropertyVariables>
              <java.util.logging.manager>org.jboss.logmanager.LogManager</java.util.logging.manager>
              <maven.home>${maven.home}</maven.home>
              <maven.repo>${settings.localRepository}</maven.repo>
              <!-- passed to quarkus prod tests for tracking of coverage -->
              <jacoco.agent>${settings.localRepository}/org/jacoco/org.jacoco.agent/${jacoco.version}/org.jacoco.agent-${jacoco.version}-runtime.jar=destfile=${project.build.directory}/jacoco-it.exec,append=true,includes=io/vanillabp/integration/deployment/**:io/vanillabp/integration/adapter/migration/**:io/vanillabp/integration/runtime/**,sessionid=anonymous-session-id</jacoco.agent>
              <maven.project.version>${project.version}</maven.project.version>
            </systemPropertyVariables>
          </configuration>
        </plugin>
        <plugin>
          <artifactId>maven-compiler-plugin</artifactId>
          <configuration>
            <parameters>true</parameters>
          </configuration>
        </plugin>
      </plugins>
    </pluginManagement>
  </build>
</project>
