package io.vanillabp.adapter.dummy.runtime;

import java.util.Map;

import org.eclipse.microprofile.config.ConfigProvider;

import io.vanillabp.integration.adapter.migration.config.MigrationAdapterProperties;
import jakarta.enterprise.context.ApplicationScoped;
import jakarta.enterprise.inject.Any;
import jakarta.enterprise.inject.Instance;
import jakarta.enterprise.inject.Produces;

/**
 * Provides the dummy adapter's {@link MigratableProcessService} as a CDI bean picked up
 * by the process service beans generated by the VanillaBP Quarkus integration. The
 * adapter ID is resolved from the configuration (first adapter of type "dummy").
 * <p>
 * For testing the two-phase workflow start, the property
 * <code>dummy-adapter.two-phase-commit</code> forces
 * {@link MigratableProcessService#needsTwoPhaseCommitForStartingWorkflows()} to return
 * <code>true</code>, and optional {@link DummyPhaseTwoListener} beans are notified on
 * phase two.
 */
@ApplicationScoped
public class DummyProcessServiceProducer {

  public static final String ADAPTER_TYPE = "dummy";

  /**
   * The property forcing the dummy adapter to require a two-phase commit for starting
   * workflows. Used by integration tests of
   * {@link io.vanillabp.integration.adapter.spi.PhaseTwoOutbox} implementations.
   */
  public static final String PROPERTY_TWO_PHASE_COMMIT = "dummy-adapter.two-phase-commit";

  @Produces
  public MigratableProcessService<Object> dummyMigratableProcessService(
      final MigrationAdapterProperties properties,
      @Any final Instance<DummyPhaseTwoListener> phaseTwoListeners) {

    final var adapterId = properties
        .adapterTypes()
        .entrySet()
        .stream()
        .filter(adapter -> ADAPTER_TYPE.equals(adapter.getValue()))
        .map(Map.Entry::getKey)
        .findFirst()
        .orElse("");

    final var needsTwoPhaseCommit = ConfigProvider
        .getConfig()
        .getOptionalValue(PROPERTY_TWO_PHASE_COMMIT, Boolean.class)
        .orElse(Boolean.FALSE);

    return new MigratableProcessService<>(adapterId, needsTwoPhaseCommit, phaseTwoListeners);

  }

}
