package io.vanillabp.adapter.dummy.runtime;

import java.util.Map;

import io.vanillabp.integration.adapter.migration.config.MigrationAdapterProperties;
import jakarta.enterprise.context.ApplicationScoped;
import jakarta.enterprise.inject.Produces;

/**
 * Provides the dummy adapter's {@link MigratableProcessService} as a CDI bean picked up
 * by the process service beans generated by the VanillaBP Quarkus integration. The
 * adapter ID is resolved from the configuration (first adapter of type "dummy").
 */
@ApplicationScoped
public class DummyProcessServiceProducer {

  public static final String ADAPTER_TYPE = "dummy";

  @Produces
  public MigratableProcessService<Object> dummyMigratableProcessService(
      final MigrationAdapterProperties properties) {

    final var adapterId = properties
        .getAdapters()
        .entrySet()
        .stream()
        .filter(adapter -> ADAPTER_TYPE.equals(adapter.getValue()))
        .map(Map.Entry::getKey)
        .findFirst()
        .orElse("");

    return new MigratableProcessService<>(adapterId);

  }

}
