package io.vanillabp.integration.adapter.spi;

/**
 * The common interface of the platform integrations' process-service beans (e.g. the
 * Spring Boot <code>ProcessServiceSpringBean</code> or the bean generated by the
 * Quarkus extension) for executing the second phase of two-phase committed BPMS calls.
 * <p>
 * For every method of <code>io.vanillabp.spi.process.ProcessService</code> requiring a
 * two-phase commit there will be a corresponding phase-two method in this interface.
 * Implementations delegate to the migration adapter's
 * <code>MigrationProcessService</code> of the workflow the call belongs to - the same
 * instance which scheduled the call through a {@link PhaseTwoOutbox} in phase one.
 * There the adapter to be used is determined: starting a workflow always uses the
 * adapter of the highest priority, whereas other operations (message correlation,
 * completing tasks, etc.) probe the prioritized adapters to find the BPMS the workflow
 * instance is running in.
 * <p>
 * Calls are routed to the right instance by the platform's {@link PhaseTwoDispatch}
 * bean using {@link #getWorkflowModuleId()} and {@link #getBpmnProcessId()}.
 */
public interface ProcessServicePhaseTwo {

  /**
   * @return The ID of the workflow module the process service belongs to
   */
  String getWorkflowModuleId();

  /**
   * @return The BPMN process ID the process service is for
   */
  String getBpmnProcessId();

  /**
   * @return The class of the workflow aggregate (used to convert serialized aggregate
   *         IDs back to the aggregate's ID type)
   */
  Class<?> getWorkflowAggregateClass();

  /**
   * Executes phase two of starting a workflow: the adapter of the highest priority
   * (the one used in phase one) is determined and its
   * {@link MigratableProcessService#startWorkflowPhaseTwo(Object)} is called.
   * <p>
   * <strong>Idempotency contract:</strong> Since {@link PhaseTwoOutbox}
   * implementations provide at-least-once semantics, this method may be called
   * repeatedly for the same parameters (e.g. after a crash between dispatching the
   * call and marking the outbox entry as processed). The triple
   * <code>workflowModuleId + bpmnProcessId + workflowAggregateId</code> is the
   * idempotency key - see {@link MigratableProcessService#startWorkflowPhaseTwo(Object)}.
   *
   * @param workflowAggregateId The ID of the workflow aggregate (in its original type)
   */
  void startWorkflowPhaseTwo(
      Object workflowAggregateId);

}
