<?xml version="1.0" encoding="UTF-8"?>
<project xmlns="http://maven.apache.org/POM/4.0.0" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xsi:schemaLocation="http://maven.apache.org/POM/4.0.0 http://maven.apache.org/xsd/maven-4.0.0.xsd">
  <modelVersion>4.0.0</modelVersion>

  <parent>
    <groupId>io.vanillabp</groupId>
    <artifactId>adapters-common</artifactId>
    <version>0.0.1-SNAPSHOT</version>
  </parent>

  <artifactId>jacoco-report</artifactId>
  <packaging>pom</packaging>
  <name>JaCoCo Report</name>

  <dependencies>
    <dependency>
      <groupId>io.vanillabp.adapter</groupId>
      <artifactId>migration-adapter</artifactId>
      <version>${project.version}</version>
      <scope>compile</scope>
    </dependency>
    <!--
    <dependency>
      <groupId>io.vanillabp</groupId>
      <artifactId>vanillabp-quarkus-integration</artifactId>
      <version>${project.version}</version>
      <scope>compile</scope>
    </dependency>
    <dependency>
      <groupId>io.vanillabp</groupId>
      <artifactId>vanillabp-quarkus-integration-deployment</artifactId>
      <version>${project.version}</version>
      <scope>compile</scope>
    </dependency>
    <dependency>
      <groupId>io.vanillabp</groupId>
      <artifactId>vanillabp-spring-boot-support</artifactId>
      <version>${project.version}</version>
      <scope>compile</scope>
    </dependency>
    -->
  </dependencies>

  <profiles>
    <profile>
      <id>jacoco</id>
      <activation>
        <activeByDefault>false</activeByDefault>
      </activation>
      <build>
        <plugins>

          <plugin>
            <groupId>org.jacoco</groupId>
            <artifactId>jacoco-maven-plugin</artifactId>
            <executions>
              <execution>
                <goals>
                  <goal>report-aggregate</goal>
                </goals>
                <phase>verify</phase>
                <configuration>
                  <dataFileIncludes>
                    <dataFileInclude>**/jacoco.exec</dataFileInclude>
                  </dataFileIncludes>
                  <outputDirectory>${project.reporting.outputDirectory}/jacoco-aggregate</outputDirectory>
                </configuration>
              </execution>
            </executions>
          </plugin>
          <plugin>
            <artifactId>maven-antrun-plugin</artifactId>
            <executions>
              <execution>
                <goals>
                  <goal>run</goal>
                </goals>
                <phase>verify</phase>
                <configuration>
                  <target>
                    <echo message="compile classpath"></echo>
                    <property name="target.dir" value="target/site/jacoco-aggregate"></property>
                    <fileset dir="${target.dir}" id="src.file">
                      <include name="index.html"></include>
                    </fileset>
                    <copy id="result.file" tofile="${target.dir}/shields-io.json">
                      <fileset refid="src.file"></fileset>
                    </copy>
                    <!--
										<replaceregexp match="^.*Total.*?ctr2&quot;&gt;" replace="">
											<fileset refid="result.file" />
										</replaceregexp>
										<replaceregexp match="%.*$" replace="%">
											<fileset refid="result.file" />
										</replaceregexp>
-->
                  </target>
                </configuration>
              </execution>
            </executions>
          </plugin>
        </plugins>
      </build>
    </profile>
  </profiles>
</project>
