<?xml version="1.0" encoding="UTF-8"?>
<project xmlns="http://maven.apache.org/POM/4.0.0" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xsi:schemaLocation="http://maven.apache.org/POM/4.0.0 https://maven.apache.org/xsd/maven-4.0.0.xsd">
  <modelVersion>4.0.0</modelVersion>

  <parent>
    <groupId>io.vanillabp</groupId>
    <artifactId>quarkus-integration-parent</artifactId>
    <version>0.0.1-SNAPSHOT</version>
  </parent>

  <groupId>io.vanillabp.quarkus</groupId>
  <artifactId>integration-tests-parent</artifactId>
  <packaging>pom</packaging>
  <name>Quarkus integration - Integration tests parent</name>

  <modules>
    <module>test-applications</module>
    <module>main-integration-test</module>
    <module>workflowmodule-integration-tests</module>
  </modules>

  <dependencyManagement>
    <dependencies>
      <dependency>
        <groupId>io.vanillabp</groupId>
        <artifactId>test-utils</artifactId>
        <version>0.0.1-SNAPSHOT</version>
        <scope>test</scope>
      </dependency>
    </dependencies>
  </dependencyManagement>

  <build>
    <pluginManagement>
      <plugins>
        <!-- configure JaCoCo for all sub-modules -->
        <plugin>
          <groupId>org.jacoco</groupId>
          <artifactId>jacoco-maven-plugin</artifactId>
          <executions>
            <execution>
              <id>prepare-agent-integration</id>
              <goals>
                <goal>prepare-agent-integration</goal>
              </goals>
              <configuration>
                <excludes>
                  <!-- exclude tests and sample code by explicitly only including code to be tested -->
                  <exclude>io/vanillabp/integration/test</exclude>
                  <exclude>io/vanillabp/integration/it</exclude>
                </excludes>
                <append>true</append>
              </configuration>
            </execution>
          </executions>
        </plugin>
      </plugins>
    </pluginManagement>
    <plugins>
      <!-- run integration tests in every sub-module -->
      <plugin>
        <artifactId>maven-failsafe-plugin</artifactId>
        <executions>
          <execution>
            <goals>
              <goal>integration-test</goal>
              <goal>verify</goal>
            </goals>
            <configuration>
              <!-- show LOG only in case of errors (last line of file will be printed) -->
              <redirectTestOutputToFile>true</redirectTestOutputToFile>
              <reportsDirectory>${project.build.directory}/failsafe-reports</reportsDirectory>
              <systemPropertyVariables>
                <quarkus.log.level>ERROR</quarkus.log.level>
              </systemPropertyVariables>
            </configuration>
          </execution>
        </executions>
      </plugin>
    </plugins>
  </build>
</project>
